### ISSUE TITLE
Switch default piops away from 2000

### ISSUE THREAD

**Issue by jamiegs** [hudl/Tyr#34]
We should make the default pIOPS a bit more reasonable so testing doesn't cost so much. For any new multiverse clusters I've been using 500 pIOPS.

**Comment by citruspi** [comment]
So I just took a quick look and it looks like the default IOPS value for the data volume on MongoDB data nodes is `3000` when it's in production and `0` otherwise. It has been since 3b4ec03bd1f2fd48d20c93ed9181f9ed036c0c8c when the `data_volume_iops` argument was introduced. 

However, the `replace_server` function in the `tyr.utilities.replace_mongo_server` module specifies a default value of `2000` for the `data_volume_iops` argument. I'm probably going to make most of the default values for the arguments for that function - `environment`, `instance_type`, `availability_zone`, `replica_set_index`, `data_volume_size`, `data_volume_iops`, `mongodb_package_version` - `None` so that the default values specified in the actual modules representing the nodes are respected.
