### ISSUE TITLE
Fill in values for DNS record log messages

### ISSUE THREAD

**Issue by jamiegs** [hudl/Tyr#46]
The log records for creating route53 show the template placeholder.  I think it'd be more clear what was going on if it actually had the values in there.  This would just be nice to have, If it's too much work to change it's ok to leave it.

Examples:
```
12:51:03 [MongoConfigNode] INFO: Routing Hosted Zone {'records': [{'type': 'CNAM
E', 'name': '{hostname}.', 'value': '{private_dns_name}', 'ttl': 60}], 'id': {'t
est': 'ZXXFTW7F1WFIS', 'prod': 'Z1LKTAOOYM3H8T', 'stage': 'Z24UEMQ8K6Z50Z'}}


12:51:03 [MongoConfigNode] INFO: Adding DNS record {'type': 'CNAME', 'name': '{h
ostname}.', 'value': '{private_dns_name}', 'ttl': 60}
```

**Comment by citruspi** [comment]
> The log records for creating route53 show the template placeholder. I think it'd be more clear what was going on if it actually had the values in there.

So, here's the relevant code:

```python
self.log.info('Adding DNS record {record}'.format(record=record))

formatting_params = {
    'hostname': self.hostname,
    'name': self.name,
    'instance_id': self.instance.id,
    'vpc_id': self.instance.vpc_id,
    'ip_address': self.instance.ip_address,
    'dns_name': self.instance.dns_name,
    'private_ip_address': self.instance.private_ip_address,
    'private_dns_name': self.instance.private_dns_name,
    'dns_zone': self.hostname[len(self.name)+1:]
}

name = record['name'].format(**formatting_params)
value = record['value'].format(**formatting_params)

self.log.info('Using record name {name}'.format(name=name))
self.log.info('Using record value {value}'.format(value=value))
```

The second log message you provided (`INFO: Adding DNS record`) comes from the first log statement. The idea is that the user should know what DNS record is currently being processed. Then, the actual values for the record are logged so the user knows what exactly is being published.

> This would just be nice to have, If it's too much work to change it's ok to leave it.

It wouldn't really be any work. The new code would look something like

```python
formatting_params = {
   ...
}

record['name'] = record['name'].format(**formatting_params)
record['value'] = record['value'].format(**formatting_params)

self.log.info('Adding DNS record {record}'.format(record=record))
```

(You'd also need to adjust the couple lines after that which actually create and update the DNS records to use `record['name']` and `record['value']` instead of `name` and `value`).

I'd be interested in a solution where we have two log statements - one with the record template, and one with the processed record.

The first log message you provided (`INFO: Routing Hosted Zone`) is simply a notice to the user about which DNS zone is currently being processed. The DNS zones

```python
{
    'records': [
        {
            'type': 'CNAME',
            'name': '{hostname}.',
            'value': '{private_dns_name}',
            'ttl': 60
        }
    ],
    'id': {
        'test': 'ZXXFTW7F1WFIS',
        'prod': 'Z1LKTAOOYM3H8T',
        'stage': 'Z24UEMQ8K6Z50Z'
    }
}
```

don't really have an ID or identifying marker as far as `Tyr` is concerned, so it's not like it can print

> 12:51:03 [MongoConfigNode] INFO: Routing Hosted Zone zone-kroslsf

So, it just dumps the whole DNS zone.

**Comment by jamiegs** [comment]
oh, yeah that's fine with leaving the first one the way it is.. I think I copy and pasted the wrong line actually
