### ISSUE TITLE
Only check for Stackdriver credentials when needed

### ISSUE THREAD

**Issue by alexdebrie** [hudl/Tyr#76]
The [utilities/stackdriver](https://github.com/hudl/Tyr/blob/master/tyr/utilities/stackdriver.py#L20) module checks for Stackdriver credentials set as environment variables and exits if they are not present. A function from that module is imported to be used in the `terminate` method in the base `Server` class. Because of this, Tyr will exit when trying to spin up any server if those environment variables aren't set, even though Stackdriver isn't used in server creation. 

I'd suggest moving the credential checks to be within the functions where they're needed.

**Comment by citruspi** [comment]
The reason that we don't check for credentials 

> within the functions where they're needed

is that we're not entirely sure _when_ they will be needed.

For example, if I provision a node and then need to terminate it, those environment variables need to be set. If they're checked for at the beginning, before I even provision anything, then I know we'll be fine to terminate the node. 

If I provision a node and those variables are only checked for when I call `terminate`, then there's a chance that those variables won't be set when they're needed. Of course, at that point, Tyr could prompt the user for those values and then set them with `os.putenv` but then we're making the assumption that a user is always present when Tyr is running.

Having said that, just because those environment variables are set doesn't mean that the credentials work - we read from the environment variables on start, but we never check the validity of the credentials until we start making API calls.

So, two points:

1. At some point (within 1 month?), we're going to confirm the credentials work after we read them, instead of waiting until we need to use them
2. Also at some point (within 1.5-2 months?) those environment variables will be moved to a configuration file, so you won't need to specify them every time.

**Comment by citruspi** [comment]
Stackdriver is no longer part of the stack.  #133
